#!/bin/bash
# pm2 entrypoint for Cyrus — starts `cyrus` with a sanitized environment.
# Register THIS script with pm2, never the `cyrus` binary directly (see
# README Startup / Gotchas). Safe to run directly too; forwards any args to
# `cyrus` (e.g. `./cyrus-start.sh self-add-repo <url>`).
#
# Requires: cyrus-env.sh in the same directory (see cyrus-env.sh.template in
# the repo root, or run setup.sh) — used for CYRUS_BIN_FALLBACK only.
#
# WHY THIS EXISTS: pm2 snapshots the shell environment at `pm2 start` time
# and replays it on every restart. If that shell was opened from a macOS GUI
# terminal (Hyper, iTerm, etc.), it can carry XPC_FLAGS (e.g. "0x2"), which
# breaks the Claude Code CLI's network stack — every Cyrus session then dies
# with "API Error: Unable to connect to API (ConnectionRefused /
# FailedToOpenSocket)" after 10 retries, while Linear webhooks keep working.
# A session env with only XPC_FLAGS added reproduces the failure, and
# removing it resolves it — isolating XPC_FLAGS as the cause.
#
# Stripping it here at exec time makes the fix immune to where pm2 is
# (re)started from.
unset XPC_FLAGS XPC_SERVICE_NAME

# Also strip Claude Code harness vars that leak in when pm2 is started from
# inside a Claude Code session (CLAUDECODE, CLAUDE_CODE_CHILD_SESSION,
# CLAUDE_CODE_SESSION_ID, ...). Cyrus's child sessions must not inherit
# another session's identity. CLAUDE_CODE_OAUTH_TOKEN is kept (auth).
while IFS= read -r v; do
  case "$v" in
    CLAUDE_CODE_OAUTH_TOKEN) ;;
    *) unset "$v" ;;
  esac
done < <(env | grep -oE '^(CLAUDE|ANTHROPIC)[A-Z_]*' )
unset AI_AGENT

echo "[cyrus-start] env sanitized (XPC_FLAGS + Claude harness vars stripped); launching cyrus"

# CYRUS_BIN_FALLBACK covers the case where pm2's sanitized env has a PATH
# that doesn't include the cyrus binary (see cyrus-env.sh, generated by setup.sh).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=cyrus-env.sh
source "$SCRIPT_DIR/cyrus-env.sh"

CYRUS_BIN="$(command -v cyrus)"
if [ -z "$CYRUS_BIN" ]; then
  CYRUS_BIN="$CYRUS_BIN_FALLBACK"
fi
exec "$CYRUS_BIN" "$@"
